init_prompts:
  - var: PREFIX
    prompt: "Where should built binaries and headers be installed?"
    default: "./install"
    options: ["./install", "/usr/local", "Custom (type it yourself)"]

  - var: BUILD_TYPE
    prompt: "Select default CMake build type:"
    default: "Release"
    options: ["Release", "Debug", "RelWithDebInfo", "MinSizeRel"]

  - var: BUILD_VARIANT
    prompt: "Which library variant should executables link against?"
    default: "static"
    options: ["debug", "memory", "static", "shared"]
