authors:
  - andy_curtis

license_profile: apache-2.0

contributors:
  andy_curtis:
    name: Andy Curtis
    email: contactandyc@gmail.com
    contact: "Andy Curtis <contactandyc@gmail.com>"
    author: "Andy Curtis <contactandyc@gmail.com> linkedin.com/in/andycurtis github.com/contactandyc"
    start_year: 1998

copyrights:
  - contributors.andy_curtis

contacts:
  - role: "Maintainer"
    entity: contributors.andy_curtis
